### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by djogopatrao** [slotek/dsk2nib#1]
When I compiled, it yielded the error:

nib2dsk.c: In function ‘main’:
nib2dsk.c:82:9: error: ‘S_IREAD’ undeclared (first use in this function)
         S_IREAD | S_IWRITE ) ) == -1 )
         ^
nib2dsk.c:82:9: note: each undeclared identifier is reported only once for each function it appears in
nib2dsk.c:82:19: error: ‘S_IWRITE’ undeclared (first use in this function)
         S_IREAD | S_IWRITE ) ) == -1 )
                   ^
Makefile:15: recipe for target 'nib2dsk.o' failed

Solution: add 
#include <sys/stat.h>
in both dsk2nib.c and nib2dsk.c

**Comment by slotek** [comment]
Fixed. Thank you!
